[[redirects]]
from = "https://jgrandcommodities.com/*"
to = "/company/:splat"
status = 200
force = true

[[redirects]]
from = "https://www.jgrandcommodities.com/*"
to = "/company/:splat"
status = 200
force = true